language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=default
- EMBER_TRY_SCENARIO=ember-1.13
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: npm
  email: null@affinitygamescollective.org
  api_key:
    secure: xNT4ZSlk9TWaC6PsnlIDqFx3HXFB48Tt2dRQ5jRDxGgQVfRSIHhRzgn3ziE54ILe2lg0omvuv0PvqTa89jIyqPYMyPSkFZvo764kZOd1mczIHlKHSagthqU1mpvPnPxLJRj4v9TL3TX6d5ZcGEsFuG8GIPuIlV3ega5PCSHIIMogq9LV/k3QaDAhWuJAHgrFSEjO4B5TqImvPVIPTOcBfh/DylA71SihxTPQ2ToEPzkHAdtuWIubfovy5J/I4nsFuK+UWuLNxmdRNMalRBRcAaWU9dNEtMbNhyd8Kl2Ms1uAbi/TgTwrd0gSVO6dWfa6edvZPztc18Im9MCsIPEVO250ixJdTxImugyJgbDF2QMIBLkTed/yaayLMppfEqrpBiWST95l9SsjfB16rzCl6YN9MiNa1VR3AXpbW8oBIwFTRxKbSqHXGDCiqs71gd3ucFULMZBK+79hwQN8CLJiQFpPPH2D5DTEK2vTh1C3qSrDn5nDuwxzrMs1t7zm9LY/eyA5EOpfcGecVAYyX9hcLUXZCb7V3xT62USw94m1+MpxpoD5GF19q7MP+kmorU9n2OGgdh03G1Xmb7iKFKCfW4Kq8ycnGYOXMgdBUe4xYM8u1q/QJIRfrxVpWxRVhBfdra9RFEnMQhDZOBVMwFVwFoXTz2hQ+Knw4h0ak6eXGr4=
  on:
    tags: true
    repo: null-null-null/ember-message-bus
